---

#master_ip: "{{ hostvars[groups['master'][0]]['ansible_default_ipv4'].address | default(groups['master'][0]) }}"
master_ip: "{{ hostvars[groups['master'][0]]['ansible_eth1'].ipv4.address | default(groups['master'][0]) }}"
